### ISSUE TITLE
not work in VS 2015 RTM

### ISSUE THREAD

**Issue by chrishaly** [Skybladev2/CSharpOutline2015#1]
Hi C# Outline Team,

Thank you for provide so useful tool.

It's not work in vs 2015 RTM. I Found you already noticed on visualstudiogallery as following:

> NOT WORKING: This extension is not working with the final version of Visual Studio 2015. However, it works with VS 2015 RC. This issue is under investigation.

Just want use this plugin as early as possible. Could I know when will it work estimate?

Thank your.

**Comment by Skybladev2** [comment]
Hello, @chrishaly 
I tried to launch it with VS 2015 Enterprise final release trial, and it seems not to work the first time.
But next day all of sudden it started working without any changes and even without VS restart.
So please post you VS environment info (Help -> About Microsoft Visual Studio), I'll try to find out what causes it.
Thanks in advance.

**Comment by MuiBienCarlota** [comment]
Hi Skybladev2 (continuation of my visualstudiogallery initial review),

I've tested on 2 machines (one Win10 RTM and One Win7 SP1, both x64) with same result: your extension is loaded but no added minus sign (for exemple on 'if' statement).

Both machines have quite same extensions loaded:
- AnkhSvn 2.5.12703.45
- Code Alignment 12.0
- Resharper Platform VS14 
- and other VS2015 'standard' extensions from Microsoft and Xamarin.

CLangFormat is only on one machine.

This is also my AboutBox:
![vs2015 rtm about](https://cloud.githubusercontent.com/assets/4465371/8959399/eb81b038-360a-11e5-9c5c-9ba94887feb3.png)

Let me know if I can help.

Thanks, your exension is very usefull.

**Comment by Skybladev2** [comment]
Hello, @MuiBienCarlota!
Glad you show me this details.
Currently I have some troubles with VS 2015 - it crashes on my real host, but works fine (including C# outline extension) on my virtual machine.
The only difference I note so far is that my .NET Framework Version is 4.6.00081, while your is 4.6.00079. However, I do not think it is the cause of the problem.

I plan to release special debug version(s) of the extension (2013 and 2015) to check what happens inside of it.
This is not a fast process, because now I have much less motivation to deal with it than 4 years ago, even if I don't like to get 1 points :)
Anyway, please wait until I release this debug versions, because I absolutely do not understand what goes wrong with my extension.

**Comment by MuiBienCarlota** [comment]
You've right about 79/81 not beeing the problem: .Net 4.6.00079 is only on my Win10 10240 machine and I've 4.6.00081 on Win7 one (but with same result).
Your crash is very strange. I had no problem on any machine except important slowdown with VS2015 RTM and Resharper 9.1.2 (but it was corrected with 9.1.3 see [ReSharper 9.1.3 to the Rescue](http://blog.jetbrains.com/dotnet/2015/07/24/resharper-9-1-3-to-the-rescue/)). Do you have Resharper on on your real host?
I'll wait for your debug version to be able to give you feedback

**Comment by MuiBienCarlota** [comment]
Regarding 79/81 difference, Perhaps it's only related the fact that .Net is supposed to have sligthly different version in Win 10 and non Win 10 as seen on MSDN [Detecting the .NET Framework](https://msdn.microsoft.com/en-us/library/ee942965%28v=vs.110%29.aspx):

| Version | Value of the Release DWORD |
| --- | --- |
| .NET Framework 4.6 installed on Windows 10 | 393295 |
| .NET Framework 4.6 installed on all OS versions other than Windows 10 | 393297 |

**N.B.** : Release refers to a registry key in HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Full.

**Comment by Skybladev2** [comment]
No, I have no Resharper, it crashes with exactly same error: https://connect.microsoft.com/VisualStudio/feedback/details/1342588/roslyn-package-failed-to-load-correctly-installing-2015rc

**Comment by Skybladev2** [comment]
@chrishaly, @MuiBienCarlota 
Please check version 1.0.2. It should work now with VS 2015 final release.

**Comment by MuiBienCarlota** [comment]
Great! It works.
I was trying to find what have changed but I've being stopped by the amount of modification. Was it  a complicated evolution?

**Comment by MuiBienCarlota** [comment]
Nevertheless, a great thanks for your prompt solution and for your usefull extension.

**Comment by Skybladev2** [comment]
@MuiBienCarlota I could not find the cause of it, so I grabbed the latest version of the [ancestor](https://jsoutlining11.codeplex.com/), modified it (again) and commited the result.
