### ISSUE TITLE
Can't install on Visual Studio 2015 for Web

### ISSUE THREAD

**Issue by DrewLandgrave** [Skybladev2/CSharpOutline2015#2]
Can't get it to install on the "for Web" version.  Install log:

> 8/17/2015 8:02:20 AM - Microsoft VSIX Installer
> 8/17/2015 8:02:20 AM - -------------------------------------------
> 8/17/2015 8:02:20 AM - Initializing Install...
> 8/17/2015 8:02:20 AM - Extension Details...
> 8/17/2015 8:02:20 AM -  Identifier      : CSharpOutline2015.Skyblade.3003efc7-c6f4-4da3-952e-32644a07ef0f
> 8/17/2015 8:02:20 AM -  Name            : C# outline 2015
> 8/17/2015 8:02:20 AM -  Author          : Skyblade
> 8/17/2015 8:02:20 AM -  Version         : 1.0.2
> 8/17/2015 8:02:20 AM -  Description     : Adds all braces {} outlining for C# editor.
> 8/17/2015 8:02:20 AM -  Locale          : en-US
> 8/17/2015 8:02:20 AM -  MoreInfoURL     : 
> 8/17/2015 8:02:20 AM -  InstalledByMSI  : False
> 8/17/2015 8:02:20 AM -  SupportedFrameworkVersionRange : [4.5,)
> 8/17/2015 8:02:20 AM - 
> 8/17/2015 8:02:20 AM -  Supported Products : 
> 8/17/2015 8:02:20 AM -      Microsoft.VisualStudio.IntegratedShell
> 8/17/2015 8:02:20 AM -          Version : [14.0]
> 8/17/2015 8:02:20 AM -      Microsoft.VisualStudio.Pro
> 8/17/2015 8:02:20 AM -          Version : [14.0]
> 8/17/2015 8:02:20 AM -      Microsoft.VisualStudio.Premium
> 8/17/2015 8:02:20 AM -          Version : [14.0]
> 8/17/2015 8:02:20 AM -      Microsoft.VisualStudio.Ultimate
> 8/17/2015 8:02:20 AM -          Version : [14.0]
> 8/17/2015 8:02:20 AM - 
> 8/17/2015 8:02:20 AM -  References      : 
> 8/17/2015 8:02:20 AM - 
> 8/17/2015 8:02:20 AM - Searching for applicable products...
> 8/17/2015 8:02:20 AM - Found installed product - Microsoft Visual Studio Express 2015 for Web
> 8/17/2015 8:02:20 AM - Found installed product - Global Location
> 8/17/2015 8:02:20 AM - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
>    at VSIXInstaller.App.InitializeInstall(Boolean isRepairSupported)
>    at VSIXInstaller.App.InitializeInstall()
>    at System.Threading.Tasks.Task.InnerInvoke()
>    at System.Threading.Tasks.Task.Execute()

**Comment by Skybladev2** [comment]
This is Express edition of Visual Studio. Extensions can not be installed on this editions: https://visualstudiomagazine.com/articles/2014/05/21/no-extensions-for-visual-studio-express.aspx
Please try VS 2015 Community edition, this is more powerful and yet free edition of Visual Studio that allows extensions to be installed: https://go.microsoft.com/fwlink/?LinkId=532606&clcid=0x409
